using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

/// <summary>
/// level end platform part (generated by LevelEndEdit.cs)
/// 
/// holds a reference to the text (x2, x3 etc.) for outside access
/// 
/// </summary>

namespace GAME
{
    public class LevelEndPart : MonoBehaviour
    {
        public TextMeshPro tm;
    }
}
